name: artifact
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: checkout
        uses: actions/checkout@v6
      - name: creating artifact
        run: |
          echo "report" > report.txt
          echo "artifact created successfully" >> report.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: report.txt
          retention-days: 1
  
  download:
    runs-on: ubuntu-latest
    steps:
      - name: downloading artifact
        uses: actions/download-artifact@v4
        with:
          name: my-artifact
      - name: showing report
        run: cat report.txt