name: "My first github workflow"
on: push

jobs:
  echo-hello-job:
    runs-on: ubuntu-latest
    steps:
      - name: Echo "Hello, GitHub Actions!"
        run: echo "Hello, GitHub Actions!"
      - name: "Get current datetime"
        run: |
          echo "Datetime: $(date +'%Y-%m-%d %H:%M:%S')"
      - name: "Repository name"
        run: echo "Repository name: ${{ github.repository }}"
