name: Pull request
on: pull_request

jobs:
  pull_request:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v6
      - name: install dependencies 
        run: pip install pytest ruff
      - name: run test
        run: pytest calcul_test.py
      - name: run linting
        run: ruff check .