name: variable & secrets
on: workflow_dispatch

jobs:
  repository-secret:
    runs-on: ubuntu-latest
    env:
      REPOSITORY_SECRET: ${{env.REPOSITORY_SECRET}}
    steps:
      - name: show secret
        run: echo "${{ env.REPOSITORY_SECRET }}"